### ISSUE TITLE
Loop is unable to end itself gracefully after pressing ^c (Or if interputted)

### ISSUE THREAD

**Issue by bhooshan100** [ajayagrawalgit/PagerCuty#1] opened 2023-12-27 14:21 UTC
Hi Ajay!

If I wish to end the loop which is acknowledging the alerts automatically in the loop fails to end gracefully.
It displays a warning as below:

May be if can get a fix for this
```
^CTraceback (most recent call last):
  File "/Users/admin/Documents/Apps/pagercuty/pagercuty.py", line 168, in <module>
    main()
  File "/Users/admin/Documents/Apps/pagercuty/pagercuty.py", line 141, in main
    pd_acknowledge_user_loop(user_id,session,user_name,ack_interval_secs)
  File "/Users/admin/Documents/Apps/pagercuty/src/pd_functions.py", line 153, in pd_acknowledge_user_loop
    time.sleep(interval)
KeyboardInterrupt
```

**Comment by ajayagrawalgit** [comment] 2023-12-27 14:33
Thanks for mentioning this @bhooshan100 😊
The issue is addressed and I will try to fix this as soon as possible.

**Comment by ajayagrawalgit** [comment] 2023-12-27 15:38
This issue has been fixed and merged to main now.
Thanks again for your valuable feedback @bhooshan100 and making PagerCuty more evolved and easy to use at the same time 😊

**Closed as completed by ajayagrawalgit** 2023-12-27 15:38 UTC
